
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "mtourhamS"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt install -y net-tools
  SHELL

  config.vm.define "mtourhamS"
  config.vm.hostname = "mtourhamS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provision "file", source: "conf/deployment.yaml", destination: "/tmp/deployment.yaml"
  config.vm.provision "file", source: "conf/app1", destination: "/tmp/app1"
  config.vm.provision "file", source: "conf/app2", destination: "/tmp/app2"
  config.vm.provision "file", source: "conf/app3", destination: "/tmp/app3"

  config.vm.provision "shell", privileged: true, path: "scripts/install.sh"
end